### ISSUE TITLE
 plate number extraction 

### ISSUE THREAD

**Issue by avico78** [MikeLud/DeepStack-Security-Camera-Models#2]
is some1 managed to extract the plate number based on the model ?
would appreciate any help

**Comment by MikeLud** [comment]
The model does not identify characters on the plate just the plate. There is a new release of CodeProject.AI coming out soon that will have a module that would identify characters on the plate.

https://www.codeproject.com/Articles/5322557/CodeProject-AI-Server-AI-the-easy-way

![image](https://user-images.githubusercontent.com/36526272/205151404-073c55bc-7150-46fe-bee7-271cd4a8f89a.png)

**Comment by MikeLud** [comment]
The model does not identify characters on the plate just the plate
