### ISSUE TITLE
Question: Remove default models or not?

### ISSUE THREAD

**Issue by MrSiO** [MikeLud/DeepStack-Security-Camera-Models#3]
This is a question concerning documentation. In one of your screenshots, it shows a list of models removed from the originals.

I found how to add your custom models reading this procedure: [https://docs.deepstack.cc/custom-models/deployment/]() (I'm using docker).

But this procedure seems to be adding custom models to the default ones and not removing the original ones... Am I right?

I wish to remove the original ones and only use yours.

Thx for any info!

**Comment by MikeLud** [comment]
> This is a question concerning documentation. In one of your screenshots, it shows a list of models removed from the originals.
> 
> I found how to add your custom models reading this procedure: https://docs.deepstack.cc/custom-models/deployment/ (I'm using docker).
> 
> But this procedure seems to be adding custom models to the default ones and not removing the original ones... Am I right?
> 
> I wish to remove the original ones and only use yours.
> 
> Thx for any info!

What software are you using to send the image to deepstack

**Comment by MrSiO** [comment]
> > This is a question concerning documentation. In one of your screenshots, it shows a list of models removed from the originals.
> > 
> > I found how to add your custom models reading this procedure: https://docs.deepstack.cc/custom-models/deployment/ (I'm using docker).
> > 
> > But this procedure seems to be adding custom models to the default ones and not removing the original ones... Am I right?
> > 
> > I wish to remove the original ones and only use yours.
> > 
> > Thx for any info!
> 
> What software are you using to send the image to deepstack

I'm using iSpy-AgentDVR.

**Comment by MikeLud** [comment]
> I'm using iSpy-AgentDVR.

I was looking at iSpy-AgentDVR instructions and it looks like you need to change the endpoint to "/v1/vision/custom/combined" if you what to use the combined model or "/v1/vision/custom/general" if you what to use the general model.

![image](https://user-images.githubusercontent.com/36526272/212526885-5e486aa5-962f-4416-be0b-4d1d6a2b775e.png)

**Comment by MrSiO** [comment]
> > I'm using iSpy-AgentDVR.
> 
> I was looking at iSpy-AgentDVR instructions and it looks like you need to change the endpoint to "/v1/vision/custom/combined" if you what to use the combined model or "/v1/vision/custom/general" if you what to use the general model.
> 
> ![image](https://user-images.githubusercontent.com/36526272/212526885-5e486aa5-962f-4416-be0b-4d1d6a2b775e.png)
> 

Great!! Will try that. Thx!!

**Comment by MikeLud** [comment]
> > > I'm using iSpy-AgentDVR.
> > 
> > 
> > I was looking at iSpy-AgentDVR instructions and it looks like you need to change the endpoint to "/v1/vision/custom/combined" if you what to use the combined model or "/v1/vision/custom/general" if you what to use the general model.
> > ![image](https://user-images.githubusercontent.com/36526272/212526885-5e486aa5-962f-4416-be0b-4d1d6a2b775e.png)
> 
> Great!! Will try that. Thx!!

Also make sure you change the Object Classes to match the model you are using.

Combined Object Classes:
person,bicycle,car,motorcycle,bus,truck,bird,cat,dog,horse,sheep,cow,bear,deer,rabbit,raccoon,fox,skunk,squirrel,pig

General Object Classes:
person,vehicle

**Comment by MrSiO** [comment]
> > > I'm using iSpy-AgentDVR.
> > 
> > 
> > I was looking at iSpy-AgentDVR instructions and it looks like you need to change the endpoint to "/v1/vision/custom/combined" if you what to use the combined model or "/v1/vision/custom/general" if you what to use the general model.
> > ![image](https://user-images.githubusercontent.com/36526272/212526885-5e486aa5-962f-4416-be0b-4d1d6a2b775e.png)
> 
> Great!! Will try that. Thx!!

Hi again!
I just want to validate something with you.

The endpoint in my iSpyDVR is in fact /v1/vision/detection
But I do not have that folder path on my deepstack docker host. 
I have a mounted volume of:  

`    volumes:
      - /home/user1/deepstack_data/Data/pytorch-models:/modelstore/detection
`
Is the **/v1/vision/detection** binded to **/modelstore/detection**  ?

If so, I guess I should create a folder  **/modelstore/detection/custom/combined** where I will put the combiend.pt file.
Then in iSpy, the endopoint would be **/va/vision/????**

I'm kinda confused about the iSpy endpoint config VS my volume on container....  :(

Thx for your lights.

**Comment by MrSiO** [comment]
> > > > I'm using iSpy-AgentDVR.
> > > 
> > > 
> > > I was looking at iSpy-AgentDVR instructions and it looks like you need to change the endpoint to "/v1/vision/custom/combined" if you what to use the combined model or "/v1/vision/custom/general" if you what to use the general model.
> > > ![image](https://user-images.githubusercontent.com/36526272/212526885-5e486aa5-962f-4416-be0b-4d1d6a2b775e.png)
> > 
> > Great!! Will try that. Thx!!
> 
> Hi again!
> I just want to validate something with you.
> 
> The endpoint in my iSpyDVR is in fact /v1/vision/detection
> But I do not have that folder path on my deepstack docker host. 
> I have a mounted volume of:  
> 
> `    volumes:
>       - /home/user1/deepstack_data/Data/pytorch-models:/modelstore/detection
> `
> Is the **/v1/vision/detection** binded to **/modelstore/detection**  ?
> 
> If so, I guess I should create a folder  **/modelstore/detection/custom/combined** where I will put the combiend.pt file.
> Then in iSpy, the endopoint would be **/va/vision/????**
> 
> I'm kinda confused about the iSpy endpoint config VS my volume on container....  :(
> 
> Thx for your lights.
> 

Anyone able to clear this up for me?
Thx.

**Comment by MikeLud** [comment]
You might want to ask your question in the iSpy repo. I do not use this software. I am using Blue Iris so I am not 100% sure on what is need to use custom models with iSpy, sorry I could not help.
The developer is working on integrating with CodeProject.AI which has all my custom models preinstalled and is more up to date then DeepStack.

https://github.com/ispysoftware/iSpy
https://www.codeproject.com/Articles/5322557/CodeProject-AI-Server-AI-the-easy-way
https://www.codeproject.com/Articles/5352147/How-to-Setup-a-Custom-AI-Model-in-Agent-DVR-Using

**Comment by MrSiO** [comment]
So true.  Thx.
I'll get back here with the infos for other users. Thx

**Comment by MikeLud** [comment]
> So true. Thx. I'll get back here with the infos for other users. Thx

Thanks

**Comment by MrSiO** [comment]
Follow iSpy answers here for those interested: https://github.com/doitandbedone/ispyagentdvr-docker/discussions/545
